Sprint 3 Usage Guide - How to test Non-blocking IEL

演示如何测试新的非阻塞交互式执行
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

print("=" * 70)
print(" Sprint 3: How to Test Non-blocking IEL")
print("=" * 70)
print()

print("[IMPORTANT] How to trigger GraphAgent mode:")
print("-" * 70)
print()
print("1. Use COMPLEX tasks (not simple!)")
print("   DON'T: 'hello?' (Too simple, goes to REACT mode)")
print("   DON'T: 'write a script with sleep' (Still simple)")
print("   DO: 'Create a complex audit script with multiple files'")
print()
print("2. OR force GraphAgent mode with /graph command")
print("   Type: /graph")
print("   Then ask your task")
print()
print("3. Complexity thresholds:")
print("   SIMPLE (0.0-0.33) -> REACT mode")
print("   MEDIUM (0.34-0.66) -> GraphAgent mode")
print("   COMPLEX (0.67-1.0) -> IEL mode")
print()
print("=" * 70)
print()
print("[Test] Try these queries to trigger GraphAgent:")
print("-" * 70)
print()
print("Option 1 (MEDIUM complexity):")
print("  '帮我写一个Python脚本，实现快速排序，包含随机数据生成，")
print("   运行后把结果写入result.txt，最后创建SUCCESS.txt'")
print()
print("Option 2 (Force GraphAgent):")
print("  1. Type: /graph")
print("  2. Then: 写fib_demo.py并运行它")
print()
print("Option 3 (Complex multi-step):")
print("  '扫描当前目录的所有.py文件，统计import语句，")
print("   分析依赖关系，生成dependency_tree.json，")
print("   最后创建report.md和SUCCESS.txt'")
print()
print("=" * 70)
print()
print("[Why this happens]")
print("-" * 70)
print("The ComplexityEvaluator intelligently routes to:")
print("  SIMPLE tasks -> REACT (fast, efficient)")
print("  MEDIUM tasks -> GraphAgent (plan before execute)")
print("  COMPLEX tasks -> IEL (safe execution)")
print()
print("To test Sprint 3, we need MEDIUM or COMPLEX tasks!")
print("=" * 70)
