export const mcpToolsData = {
  version: "1.0.0",
  categories: [
    { id: "filesystem", name: "Filesystem", icon: "Folder" },
    { id: "database", name: "Database", icon: "Database" },
    { id: "development", name: "Development", icon: "Code" },
    { id: "communication", name: "Communication", icon: "MessageSquare" },
    { id: "productivity", name: "Productivity", icon: "CheckSquare" },
    { id: "cloud", name: "Cloud", icon: "Cloud" },
    { id: "ai", name: "AI & ML", icon: "Brain" },
    { id: "utilities", name: "Utilities", icon: "Wrench" },
  ],
  tools: [
    {
      id: "filesystem",
      name: "Filesystem Server",
      description: "Access and manipulate files on your local filesystem",
      categoryId: "filesystem",
      version: "1.0.0",
      author: "ModelContextProtocol",
      installed: false,
      rating: 4.8,
      downloads: "125K",
      features: [
        "Read, write, and delete files",
        "List directory contents",
        "Search files by name/pattern",
        "File metadata access",
      ],
      installation: {
        command: "npx",
        args: ["@modelcontextprotocol/server-filesystem", "/path/to/allowed/directory"],
      },
      requirements: ["Node.js 18+", "Allowed directory path"],
    },
    {
      id: "sqlite",
      name: "SQLite Server",
      description: "Query and manage SQLite databases",
      categoryId: "database",
      version: "1.0.0",
      author: "ModelContextProtocol",
      installed: false,
      rating: 4.7,
      downloads: "98K",
      features: [
        "Execute SQL queries",
        "Read database schema",
        "Multiple database support",
        "Transaction support",
      ],
      installation: {
        command: "npx",
        args: ["@modelcontextprotocol/server-sqlite", "--db-path", "/path/to/database.db"],
      },
      requirements: ["SQLite database file"],
    },
    {
      id: "github",
      name: "GitHub Server",
      description: "Interact with GitHub repositories and issues",
      categoryId: "development",
      version: "1.0.0",
      author: "ModelContextProtocol",
      installed: false,
      rating: 4.9,
      downloads: "156K",
      features: [
        "Repository search",
        "Issue and PR management",
        "Code browsing",
        "Git operations",
      ],
      installation: {
        command: "npx",
        args: ["@modelcontextprotocol/server-github"],
      },
      requirements: ["GitHub Personal Access Token"],
    },
    {
      id: "slack",
      name: "Slack Server",
      description: "Send messages and interact with Slack workspaces",
      categoryId: "communication",
      version: "1.0.0",
      author: "ModelContextProtocol",
      installed: false,
      rating: 4.6,
      downloads: "89K",
      features: [
        "Send messages to channels",
        "Read channel history",
        "User and channel info",
        "File uploads",
      ],
      installation: {
        command: "npx",
        args: ["@modelcontextprotocol/server-slack"],
      },
      requirements: ["Slack Bot Token", "Slack App ID"],
    },
    {
      id: "postgres",
      name: "PostgreSQL Server",
      description: "Query PostgreSQL databases with full SQL support",
      categoryId: "database",
      version: "1.0.0",
      author: "ModelContextProtocol",
      installed: false,
      rating: 4.8,
      downloads: "112K",
      features: [
        "Execute SQL queries",
        "Database schema inspection",
        "Connection pooling",
        "Prepared statements",
      ],
      installation: {
        command: "npx",
        args: ["@modelcontextprotocol/server-postgres", "--connection-string", "postgresql://..."],
      },
      requirements: ["PostgreSQL database", "Connection string"],
    },
  ],
}
